version: '3'

services:
    client:
        build: ./client
        stdin_open: true
        volumes:
            - ./client/build:/opt/client/build

    server:
        build: ./server
        environment: 
            - NODE_ENV='production'
        ports:
            - 3001:3001