version: '3'

networks: 
    test:

services:
    client:
        build: ./client
        stdin_open: true
        volumes:
            - ./client/build:/opt/client/build

    server:
        build: ./server
        environment: 
            - NODE_ENV=production
            - MONGODB=mongodb
        ports:
            - 3001:3001
        links: 
            - mongodb

    mongodb:
        image: 3.6-xenial