openapi: 3.0.1
info:
  title: JSRamverk API
  description: This is a server for fetching reports for JSRamverk
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /:
    get:
      tags:
      - root
      summary: Report about me
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AboutMeReport'
  /reports:
    post:
      tags:
      - reports
      summary: Create a new report
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomingReport'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedReport'
                
        401:
          description: Invalid authentication
          
        403:
          description: Unauthenticated
    
  /reports/week/{weekNumber}:
    get:
      tags:
      - reports
      summary: Get report from specific week
      parameters:
      - name: weekNumber
        in: path
        description: ID of report to return
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedReport'
        400:
          description: Bad Request, invalid week number
        
        401:
          description: Invalid authentication
        
        403:
          description: Unauthenticated
          
          
  /register:
    post:
      tags: 
      - user
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomingUser'
      responses:
        201:
          description: Created
  
  /login:
    post:
      tags: 
      - user
      summary: Login as a registered user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomingUser'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomingUser'
        401:
          description: Invalid credentials

  /username/status/{username}:
    get:
      tags:
      - user
      summary: Get status of a particular username
      parameters:
        - name: username
          in: path
          required: true
          description: The username you want a status for
          schema:
            type: string
            
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  taken:
                    type: boolean
        
components:
  schemas:
    IncomingReport:
      type: object
      properties:
        week:
          type: integer
        content:
          type: string
        
    CreatedReport:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: string
            user_id:
              type: integer
        - $ref: '#/components/schemas/IncomingReport'
        
    AboutMeReport:
      type: object
      properties:
        content:
          type: string
          
    
    IncomingUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          
    CreatedUser:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: integer
      $ref: '#/components/schemas/IncomingUser'